/**
 * 301 redirect map for the WordPress → Next.js migration.
 *
 * Generated by /Volumes/PortableSSD/Clients/sandhurst-roofing/data-extracted/build_redirect_map.py
 * on May 26, 2026.
 *
 * Sources:
 *   1. WordPress Simple 301 Redirects plugin (12 preserved rules)
 *   2. Blog URL structure change: WP flat /slug/ → Next.js /blog/slug/ (38 redirects)
 *   3. Colour Tools URL flatten: /colour-tools/sub/ → /sub/ (2 redirects)
 *   4. Bot/crawler legacy: /tel:* and /llms.txt → / (skipped - bot garbage)
 *
 * Total: 52 active redirects (53 minus 1 already-handled by blog dynamic route).
 *
 * All marked permanent (308 status code).
 */

export interface Redirect {
  source: string;
  destination: string;
  permanent: true;
}

export const redirectMap: Redirect[] = [
  // ===== existing-simple-301 (preserved from WordPress Simple 301 Redirects plugin) =====
  { source: "/chelsey-heights/", destination: "/chelsea-heights/", permanent: true },
  { source: "/cape-schank/", destination: "/cape-schanck/", permanent: true },
  { source: "/roof-restoration/img_2236", destination: "/roof-restoration/", permanent: true },
  { source: "/guttering/img_2707", destination: "/guttering/", permanent: true },
  { source: "/colorbond", destination: "/colorbond-roofing/", permanent: true },
  { source: "/gallery", destination: "/recent-jobs/", permanent: true },
  { source: "/contact-us", destination: "/contact/", permanent: true },
  { source: "/recent-jobs/roof-restoration-pic3", destination: "/recent-jobs/", permanent: true },
  { source: "/recent-jobs/roof-restoration-pic4", destination: "/recent-jobs/", permanent: true },
  { source: "/recent-jobs/roof-restoration-pic5", destination: "/recent-jobs/", permanent: true },
  { source: "/service-area", destination: "/service-areas/", permanent: true },
  {
    source: "/5-most-common-caues-for-a-leaking-roof/",
    destination: "/5-most-common-causes-for-a-leaking-roof/",
    permanent: true,
  },

  // ===== page-structure-change (colour tools URL flatten) =====
  { source: "/colour-tools/colour-visualisation-tool/", destination: "/colour-visualisation-tool/", permanent: true },
  { source: "/colour-tools/colorbond-colour-chart/", destination: "/colorbond-colour-chart/", permanent: true },

  // ===== blog-structure-change (38 blog posts: WP flat → Next.js /blog/[slug]/) =====
  { source: "/roof-restoration-cost-melbourne/", destination: "/blog/roof-restoration-cost-melbourne/", permanent: true },
  { source: "/colorbond-roof-painting-cost/", destination: "/blog/colorbond-roof-painting-cost/", permanent: true },
  { source: "/roof-repointing-cost/", destination: "/blog/roof-repointing-cost/", permanent: true },
  { source: "/what-does-a-roof-plumber-do/", destination: "/blog/what-does-a-roof-plumber-do/", permanent: true },
  { source: "/weep-holes-in-a-tiled-roof/", destination: "/blog/weep-holes-in-a-tiled-roof/", permanent: true },
  { source: "/rust-on-your-roof-when-to-replace-roof/", destination: "/blog/rust-on-your-roof-when-to-replace-roof/", permanent: true },
  { source: "/what-is-flexible-repointing/", destination: "/blog/what-is-flexible-repointing/", permanent: true },
  { source: "/how-much-does-it-cost-to-paint-a-roof/", destination: "/blog/how-much-does-it-cost-to-paint-a-roof/", permanent: true },
  { source: "/what-is-a-roof-valley/", destination: "/blog/what-is-a-roof-valley/", permanent: true },
  { source: "/replace-or-repair-roof/", destination: "/blog/replace-or-repair-roof/", permanent: true },
  { source: "/how-long-does-a-roof-restoration-last/", destination: "/blog/how-long-does-a-roof-restoration-last/", permanent: true },
  { source: "/5-most-common-causes-for-a-leaking-roof/", destination: "/blog/5-most-common-causes-for-a-leaking-roof/", permanent: true },
  { source: "/what-does-a-full-roof-restoration-include/", destination: "/blog/what-does-a-full-roof-restoration-include/", permanent: true },
  { source: "/early-signs-you-need-a-roof-replacement/", destination: "/blog/early-signs-you-need-a-roof-replacement/", permanent: true },
  { source: "/how-roof-restorations-can-increase-your-property-value-in-melbourne/", destination: "/blog/how-roof-restorations-can-increase-your-property-value-in-melbourne/", permanent: true },
  { source: "/whats-the-difference-between-roof-repairs-and-roof-restoration/", destination: "/blog/whats-the-difference-between-roof-repairs-and-roof-restoration/", permanent: true },
  { source: "/how-to-extend-the-lifespan-of-your-roof-maintenance-tips/", destination: "/blog/how-to-extend-the-lifespan-of-your-roof-maintenance-tips/", permanent: true },
  { source: "/how-to-prepare-your-home-for-a-roof-replacement-a-homeowners-checklist/", destination: "/blog/how-to-prepare-your-home-for-a-roof-replacement-a-homeowners-checklist/", permanent: true },
  { source: "/what-do-metal-roofing-specialists-do/", destination: "/blog/what-do-metal-roofing-specialists-do/", permanent: true },
  { source: "/do-metal-roofs-need-to-be-painted/", destination: "/blog/do-metal-roofs-need-to-be-painted/", permanent: true },
  { source: "/expert-colorbond-roofing-installation/", destination: "/blog/expert-colorbond-roofing-installation/", permanent: true },
  { source: "/the-benefits-of-choosing-colorond-steel-roofing-over-traditional-tiles/", destination: "/blog/the-benefits-of-choosing-colorond-steel-roofing-over-traditional-tiles/", permanent: true },
  { source: "/how-to-choose-the-right-colorbond-roof-colour-for-your-home/", destination: "/blog/how-to-choose-the-right-colorbond-roof-colour-for-your-home/", permanent: true },
  { source: "/why-colorbond-roofing-is-the-perfect-choice-for-your-home/", destination: "/blog/why-colorbond-roofing-is-the-perfect-choice-for-your-home/", permanent: true },
  { source: "/top-benefits-of-installing-a-colorbond-roof/", destination: "/blog/top-benefits-of-installing-a-colorbond-roof/", permanent: true },
  { source: "/colorbond-roofing-vs-tile-roofing-which-is-best-for-your-home/", destination: "/blog/colorbond-roofing-vs-tile-roofing-which-is-best-for-your-home/", permanent: true },
  { source: "/how-colorbond-roofing-stands-up-to-extreme-weather/", destination: "/blog/how-colorbond-roofing-stands-up-to-extreme-weather/", permanent: true },
  { source: "/can-you-paint-a-colorbond-roof/", destination: "/blog/can-you-paint-a-colorbond-roof/", permanent: true },
  { source: "/roof-leak-repair/", destination: "/blog/roof-leak-repair/", permanent: true },
  { source: "/tile-roof-repair/", destination: "/blog/tile-roof-repair/", permanent: true },
  { source: "/emergency-roof-repair-what-homeowners-should-do-during-a-leak-or-storm/", destination: "/blog/emergency-roof-repair-what-homeowners-should-do-during-a-leak-or-storm/", permanent: true },
  { source: "/roof-painting-in-melbourne-costs-benefits-process-faqs/", destination: "/blog/roof-painting-in-melbourne-costs-benefits-process-faqs/", permanent: true },
  { source: "/the-importance-of-regular-roof-inspections-what-to-look-for/", destination: "/blog/the-importance-of-regular-roof-inspections-what-to-look-for/", permanent: true },
  { source: "/roof-inspection-by-a-professional/", destination: "/blog/roof-inspection-by-a-professional/", permanent: true },
  { source: "/the-role-of-roof-ventilation-why-proper-ventilation-is-essential/", destination: "/blog/the-role-of-roof-ventilation-why-proper-ventilation-is-essential/", permanent: true },
  { source: "/5-warning-signs-you-need-gutter-replacement-in-melbourne/", destination: "/blog/5-warning-signs-you-need-gutter-replacement-in-melbourne/", permanent: true },
  { source: "/how-to-choose-a-reliable-roofing-contractor-key-factors-to-consider/", destination: "/blog/how-to-choose-a-reliable-roofing-contractor-key-factors-to-consider/", permanent: true },
  { source: "/why-you-should-consider-professional-help-for-your-asbestos-roof-removal/", destination: "/blog/why-you-should-consider-professional-help-for-your-asbestos-roof-removal/", permanent: true },

  // ===== blog-missing-on-nextjs (pergola post - will become real once added in Task #17) =====
  { source: "/pergola-repairs-or-replacement/", destination: "/blog/pergola-repairs-or-replacement/", permanent: true },
];
